### ISSUE TITLE
Hibás hosszúsági és szélességi pozíció az adatbázisban

### ISSUE THREAD

**Issue by ratzalex** [duliczvince/RR_FR_SWP_teszt_feladat#1]
A `country` táblába betöltött hosszúsági és szélességi fok adatokkal az alábbi problémák vannak:

1. Habár _két numerikus_ értékről van szó, a megoldás mégis _egy szöveges_ mezőbe (`latlng`) tölti be azokat.
1. A betöltött értékek hibásak (kimarad belőlük a tizedespont).

**Comment by duliczvince** [comment]
Javítva

**Comment by ratzalex** [comment]
Rendben.
