### ISSUE TITLE
Betöltött országadat rekordok számolása helytelen

### ISSUE THREAD

**Issue by ratzalex** [duliczvince/RR_FR_SWP_teszt_feladat#2]
A feladatkiírás szerint a megoldás: _"Megszámolja („count”) és kiírja (konzolra vagy log fájlba) hogy hány országadat került bele
az adattáblába."_

Ezzel szemben az elkészült kód nem az adatbázis táblából számolja meg a betöltött rekordokat, hanem REST API-n ismét lekéri az országokat és annak számosságát jeleníti meg. 

Természetesen általában, ha minden jól megy ez a két szám megegyezik, de ha pl. ha nem tud kapcsolódni az adatbázishoz, akkor is kiírja, hogy: _"Országszám: 250"_, ami nem helyes.

**Comment by duliczvince** [comment]
Javítva

**Comment by ratzalex** [comment]
Rendben.
